version: "3.9"
services:
  web:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_USER: 'hiro'
      MYSQL_DATABASE: 'anekazoo'
      MYSQL_PASSWORD: 'kebersamaan@'
      MYSQL_ROOT_PASSWORD: 'kebersamaan@'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
